(function(global){
'use strict';
const P_NAMES={RR:'Reality Reckoning',IB:'Indeterminate Becoming',DE:'Disruptive Engagement',ES:'Emancipatory Shift',RA:'Radical Renewal'};
const FACET_NAMES={SL:'Systemic Literacy',PL:'Positionality Literacy',TTC:'Truth-Telling Capacity',NT:'Nonlinear Thinking',IFC:'Identity Flex in Context',EH:'Emergent Humility',IP:'Interruptive Practice',SP:'Solidarity Praxis',DD:'Dialogic Disruption',AE:'Accountable Engagement',VP:'Visionary Praxis',SR:'Systems Reorientation',TPP:'Transformative Policy Praxis',RO:'Regenerative Orientation',CC:'Collective Centering',RtR:'Return to Relation'};
const CONFIGS={
 'H-H-H':{"name":"Architect","family":"Ambassadors","zone":"Transformative Zone","descriptiveLine":"Creating coherent direction through awareness, possibility, and action.","shortDescription":"Creating coherent direction through awareness, possibility, and action.","profile":"As an Architect, you naturally integrate reality, possibility, and action into a coherent approach for leading transformative change. You create clarity in moments of complexity by helping people and organizations connect systemic awareness, adaptive thinking, and courageous action toward a shared direction.","leadershipStory":"As an Architect, you naturally integrate reality, possibility, and action into a coherent approach for leading transformative change. You create clarity in moments of complexity by helping people and organizations connect systemic awareness, adaptive thinking, and courageous action toward a shared direction.","howYouLead":"Your leadership expands as you intentionally develop these same capacities in others, making transformative leadership a collective practice rather than an individual strength.","expandingLeadershipContribution":"Your leadership expands as you intentionally develop these same capacities in others, making transformative leadership a collective practice rather than an individual strength.","uniqueContribution":"Systems Leadership","familyStrength":"Strategic Design","sharedStrength":"Sustainability","strengths":["Systems Leadership","Strategic Design","Sustainability"],"helpOthers":"Develop others to think systemically and lead collaboratively.","increaseLeadershipEffectiveness":"Create more opportunities for others to lead transformation independently.","enduringQuestion":"How am I helping others develop the same integrated leadership I bring naturally?","icon":"assets/icons/archetypes/architect-icon.svg"},
 'L-H-H':{"name":"Accelerator","family":"Ambassadors","zone":"Transformative Zone","descriptiveLine":"Transforming possibility into meaningful action.","shortDescription":"Transforming possibility into meaningful action.","profile":"As an Accelerator, you naturally approach leadership with curiosity, openness, and a desire to discover new possibilities. You lead by recognizing emerging opportunities, encouraging experimentation, and helping others move confidently toward new possibilities.","leadershipStory":"As an Accelerator, you naturally approach leadership with curiosity, openness, and a desire to discover new possibilities. You lead by recognizing emerging opportunities, encouraging experimentation, and helping others move confidently toward new possibilities.","howYouLead":"Your leadership expands as you ground emerging possibilities in a deeper understanding of reality, transforming bold ideas into meaningful and sustainable action.","expandingLeadershipContribution":"Your leadership expands as you ground emerging possibilities in a deeper understanding of reality, transforming bold ideas into meaningful and sustainable action.","uniqueContribution":"Entrepreneurial Leadership","familyStrength":"Opportunity Creation","sharedStrength":"Innovation","strengths":["Entrepreneurial Leadership","Opportunity Creation","Innovation"],"helpOthers":"Expand how others think about what is possible.","increaseLeadershipEffectiveness":"Slow down to understand the deeper context before acting.","enduringQuestion":"What deeper patterns should I understand before taking my next step?","icon":"assets/icons/archetypes/accelerator-icon.svg"},
 'H-L-H':{"name":"Advocate","family":"Ambassadors","zone":"Transformative Zone","descriptiveLine":"Challenging inequitable patterns through courageous action.","shortDescription":"Challenging inequitable patterns through courageous action.","profile":"As an Advocate, you naturally recognize difficult realities and possess the courage to respond with purposeful action. You lead by confronting harmful patterns, encouraging accountability, and creating opportunities for meaningful systemic change.","leadershipStory":"As an Advocate, you naturally recognize difficult realities and possess the courage to respond with purposeful action. You lead by confronting harmful patterns, encouraging accountability, and creating opportunities for meaningful systemic change.","howYouLead":"Your leadership expands as you explore new possibilities alongside difficult realities, allowing courageous action to become both transformative and enduring.","expandingLeadershipContribution":"Your leadership expands as you explore new possibilities alongside difficult realities, allowing courageous action to become both transformative and enduring.","uniqueContribution":"Courageous Leadership","familyStrength":"Mobilization","sharedStrength":"Courageous Communication","strengths":["Courageous Leadership","Mobilization","Courageous Communication"],"helpOthers":"Help people navigate ambiguity and complexity.","increaseLeadershipEffectiveness":"Ask more questions before deciding on a course of action.","enduringQuestion":"How might deeper curiosity strengthen the impact of my courage?","icon":"assets/icons/archetypes/advocate-icon.svg"},
 'L-H-L':{"name":"Connector","family":"Champions","zone":"Emergent Zone","descriptiveLine":"Building understanding that inspires meaningful action.","shortDescription":"Building understanding that inspires meaningful action.","profile":"As a Connector, you naturally bring people together to discover new possibilities through meaningful relationships. You lead by creating space for dialogue, building trust, and helping others uncover ideas that strengthen collaboration and shared understanding.","leadershipStory":"As a Connector, you naturally bring people together to discover new possibilities through meaningful relationships. You lead by creating space for dialogue, building trust, and helping others uncover ideas that strengthen collaboration and shared understanding.","howYouLead":"Your leadership expands as you transform the ideas and possibilities you uncover into meaningful action, helping relationships become catalysts for lasting change.","expandingLeadershipContribution":"Your leadership expands as you transform the ideas and possibilities you uncover into meaningful action, helping relationships become catalysts for lasting change.","uniqueContribution":"Relational Leadership","familyStrength":"Insight","sharedStrength":"Innovation","strengths":["Relational Leadership","Insight","Innovation"],"helpOthers":"Create space for honest dialogue and accountability.","increaseLeadershipEffectiveness":"Take meaningful action on the ideas you uncover.","enduringQuestion":"When is understanding sufficient to begin acting?","icon":"assets/icons/archetypes/connector-icon.svg"},
 'H-L-L':{"name":"Cultivator","family":"Champions","zone":"Emergent Zone","descriptiveLine":"Helping others understand reality and grow with clarity.","shortDescription":"Helping others understand reality and grow with clarity.","profile":"As a Cultivator, you naturally understand people, systems, and the realities that shape them. You lead by building trust, developing others, and creating environments where individuals gain greater clarity, confidence, and capacity for growth.","leadershipStory":"As a Cultivator, you naturally understand people, systems, and the realities that shape them. You lead by building trust, developing others, and creating environments where individuals gain greater clarity, confidence, and capacity for growth.","howYouLead":"Your leadership expands as you transform deep understanding into courageous action, helping others move from greater clarity toward meaningful and lasting change.","expandingLeadershipContribution":"Your leadership expands as you transform deep understanding into courageous action, helping others move from greater clarity toward meaningful and lasting change.","uniqueContribution":"Learning Leadership","familyStrength":"Clarity","sharedStrength":"Foresight","strengths":["Learning Leadership","Clarity","Foresight"],"helpOthers":"Create environments where others feel valued and supported.","increaseLeadershipEffectiveness":"Move from understanding to courageous action.","enduringQuestion":"What future becomes possible when I build upon what I already understand?","icon":"assets/icons/archetypes/cultivator-icon.svg"},
 'L-L-H':{"name":"Catalyst","family":"Champions","zone":"Emergent Zone","descriptiveLine":"Creating momentum by moving people toward action.","shortDescription":"Creating momentum by moving people toward action.","profile":"As a Catalyst, you naturally move ideas into action with confidence and determination. You lead by mobilizing people, creating momentum, and helping teams make meaningful progress when decisive action is needed.","leadershipStory":"As a Catalyst, you naturally move ideas into action with confidence and determination. You lead by mobilizing people, creating momentum, and helping teams make meaningful progress when decisive action is needed.","howYouLead":"Your leadership expands as you deepen your understanding before taking action, ensuring momentum is guided by wisdom as well as determination.","expandingLeadershipContribution":"Your leadership expands as you deepen your understanding before taking action, ensuring momentum is guided by wisdom as well as determination.","uniqueContribution":"Mobilizing Leadership","familyStrength":"Execution","sharedStrength":"Courageous Communication","strengths":["Mobilizing Leadership","Execution","Courageous Communication"],"helpOthers":"Mobilize people toward meaningful action.","increaseLeadershipEffectiveness":"Pause to deepen understanding before taking the next step.","enduringQuestion":"How can deeper understanding strengthen the actions I take today?","icon":"assets/icons/archetypes/catalyst-icon.svg"},
 'H-H-L':{"name":"Sensemaker","family":"Stewards","zone":"Continuity Zone","descriptiveLine":"Bringing clarity to complexity through synthesis and perspective.","shortDescription":"Bringing clarity to complexity through synthesis and perspective.","profile":"As a Sensemaker, you naturally help people make sense of complexity by recognizing patterns, connecting ideas, and synthesizing diverse perspectives. You lead by creating shared understanding that helps others recognize emerging possibilities and move toward meaningful action.","leadershipStory":"As a Sensemaker, you naturally help people make sense of complexity by recognizing patterns, connecting ideas, and synthesizing diverse perspectives. You lead by creating shared understanding that helps others recognize emerging possibilities and move toward meaningful action.","howYouLead":"Your leadership expands as you pair broad perspective with intentional follow-through, transforming shared understanding into meaningful and sustained action.","expandingLeadershipContribution":"Your leadership expands as you pair broad perspective with intentional follow-through, transforming shared understanding into meaningful and sustained action.","uniqueContribution":"Perspective Leadership","familyStrength":"Synthesis","sharedStrength":"Foresight","strengths":["Perspective Leadership","Synthesis","Foresight"],"helpOthers":"Build optimism and confidence during uncertainty.","increaseLeadershipEffectiveness":"Turn your ideas into practical next steps for others.","enduringQuestion":"What courageous action will move this possibility toward reality?","icon":"assets/icons/archetypes/sensemaker-icon.svg"},
 'L-L-L':{"name":"Stabilizer","family":"Stewards","zone":"Continuity Zone","descriptiveLine":"Providing stability while creating conditions for growth.","shortDescription":"Providing stability while creating conditions for growth.","profile":"As a Stabilizer, you naturally value stability, consistency, and dependable leadership, helping people and organizations build trust over time. You create the trust and stability that allow people and organizations to grow through change without losing their core purpose.","leadershipStory":"As a Stabilizer, you naturally value stability, consistency, and dependable leadership, helping people and organizations build trust over time. You create the trust and stability that allow people and organizations to grow through change without losing their core purpose.","howYouLead":"Your leadership expands as you embrace new possibilities alongside trusted practices, helping stability become a foundation for continued growth and transformation.","expandingLeadershipContribution":"Your leadership expands as you embrace new possibilities alongside trusted practices, helping stability become a foundation for continued growth and transformation.","uniqueContribution":"Balanced Leadership","familyStrength":"Consistency","sharedStrength":"Sustainability","strengths":["Balanced Leadership","Consistency","Sustainability"],"helpOthers":"Encourage shared responsibility for sustaining meaningful change.","increaseLeadershipEffectiveness":"Take small actions even when the outcome is uncertain.","enduringQuestion":"What new possibility is inviting me to grow beyond what is familiar?","icon":"assets/icons/archetypes/stabilizer-icon.svg"}
};
const EXPRESSIONS={
 'H-H':{name:'Transformative Liberation',leadershipImpact:'You are positioned to create lasting, equity-centered transformation by redistributing power, strengthening accountability, and embedding equitable practices.',deepeningPractice:'Continue developing other leaders, distributing responsibility, and building regenerative systems so transformation extends beyond your direct influence.'},
 'H-L':{name:'Performative Change',leadershipImpact:'You can generate visible movement toward equity, particularly when vision and policy change are supported by durable practices of renewal and accountability.',deepeningPractice:'Strengthen the regenerative conditions, relationships, and shared ownership needed to sustain change beyond initial momentum.'},
 'L-H':{name:'Regenerative Stability',leadershipImpact:'You contribute steadiness, care, and renewal that can sustain people and organizations through change.',deepeningPractice:'Pair your regenerative strengths with bolder systems redesign and policy action so stability becomes a foundation for liberation rather than continuity.'},
 'L-L':{name:'Emerging Transformation',leadershipImpact:'You are building the capacities needed to translate equity commitments into durable systems change.',deepeningPractice:'Focus on connecting vision to concrete redesign while cultivating the collective care and accountability needed to sustain the work.'}
};
const RESPONSE_VALUES={'Not at all like me':1,'Not much like me':2,'A little like me':2,'Somewhat like me':3,'Very much like me':4};
function round(v,d=0){const p=10**d;return Math.round((v+Number.EPSILON)*p)/p;}
function mean(rows){const w=rows.reduce((s,r)=>s+(r.weight||1),0);return w?rows.reduce((s,r)=>s+r.value*(r.weight||1),0)/w:null;}
function band(score,spec){return spec.developmentBands.find(b=>score>=b.min&&score<=b.max)||spec.developmentBands[spec.developmentBands.length-1];}
function hl(code,score,spec){return score>spec.highLowThresholds[code]?'H':'L';}
function collectResponses(itemSteps,inventory){const answers={}; itemSteps.forEach((step,i)=>{const checked=step.querySelector('input[type=radio]:checked'); if(checked) answers[i+1]=RESPONSE_VALUES[checked.value];});
 return inventory.items.map(item=>{const raw=answers[item.displayOrder]; if(!raw) throw new Error('Missing scored response at statement '+item.displayOrder); return {...item,rawValue:raw,scoredValue:item.reverseScored?5-raw:raw};});}
function compute(itemSteps,participant){const inventory=global.RISE_INVENTORY_SPEC,spec=global.RISE_SCORING_SPEC; if(!inventory||!spec) throw new Error('R.I.S.E. scoring specifications did not load.');
 const scored=collectResponses(itemSteps,inventory); const facets={};
 for(const row of scored){const key=row.principleCode+'_'+row.facetCode;(facets[key]??=[]).push({value:row.scoredValue,weight:row.weight,itemId:row.itemId});}
 const facetScores={}; for(const [key,rows] of Object.entries(facets)){const [pc,...fc]=key.split('_'); const raw=mean(rows); const score=round(raw*25,1); facetScores[key]={principleCode:pc,facetCode:fc.join('_'),name:FACET_NAMES[fc.join('_')]||fc.join('_'),rawMean:round(raw,3),score,band:band(score,spec),items:rows.map(r=>r.itemId)};}
 const byPrinciple={}; for(const row of scored)(byPrinciple[row.principleCode]??=[]).push({value:row.scoredValue,weight:row.weight});
 const principleScores={}; for(const code of ['RR','IB','DE','ES','RA']){const raw=mean(byPrinciple[code]||[]); const score=round(raw*25,0); principleScores[code]={code,name:P_NAMES[code],rawMean:round(raw,3),score,band:band(score,spec)};}
 const configPattern=['RR','IB','DE'].map(c=>hl(c,principleScores[c].score,spec)).join('-'); const expressionPattern=['ES','RA'].map(c=>hl(c,principleScores[c].score,spec)).join('-');
 const configuration={pattern:configPattern,...CONFIGS[configPattern]}; const expression={pattern:expressionPattern,...EXPRESSIONS[expressionPattern]};
 const ordered=Object.values(principleScores).sort((a,b)=>b.score-a.score); const strongestP=ordered[0], edgeP=[...ordered].sort((a,b)=>a.score-b.score)[0];
 const strongest={code:strongestP.code,name:strongestP.name,descriptiveLabel:strongestP.name+' Leadership',leadershipContribution:`Your strength in ${strongestP.name} helps you ${strongestP.code==='RR'?'see systems clearly, name inequity, and ground decisions in truth':strongestP.code==='IB'?'navigate uncertainty, learn with others, and create adaptive possibilities':strongestP.code==='DE'?'translate values into courageous action and interrupt harmful patterns':strongestP.code==='ES'?'redesign systems, policy, and power toward equity and liberation':'sustain transformation through care, regeneration, and collective responsibility'}.`};
 const edge={code:edgeP.code,name:edgeP.name,developmentEdge:`Deepening ${edgeP.name} will expand your ability to ${edgeP.code==='RR'?'connect everyday outcomes to systems, power, and historical patterns':edgeP.code==='IB'?'remain open, adaptive, and generative amid uncertainty':edgeP.code==='DE'?'act courageously and consistently when inequity or harm is present':edgeP.code==='ES'?'move from aspiration toward systems redesign and policy change':'embed renewal, repair, and collective care into sustained practice'}.`};
 const name=(participant.name||'Participant').trim();
 return {version:inventory.version,calibration:spec.calibration||null,generatedAt:new Date().toISOString(),date:new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date()),name,email:participant.email||'',organization:participant.organization||participant.teamName||'',role:participant.role||'',participant,responses:scored.map(x=>({itemId:x.itemId,displayOrder:x.displayOrder,rawValue:x.rawValue,scoredValue:x.scoredValue})),facetScores,principleScores,configuration,expression,strongest,edge};}
 global.RISE_SCORING_ENGINE={compute};
})(window);
