(function(){
'use strict';
const state={started:false,startWallMs:0,lastSegmentWallMs:0,segmentVisible:true,activeMs:0,inactiveMs:0,excludedActiveMs:0,exclusionDepth:0,exclusionStartActiveMs:0,openEvents:new Map(),eventCounter:0,firstAnswered:new Set(),answers:{},itemShownAdjustedMs:{},itemLatencyMs:{},timingEvents:[],answerOrder:[],visibilityEvents:[],changedResponseCount:0,orderCounter:0};
function now(){return Date.now();}
function commitSegment(){if(!state.started)return;const t=now(),d=Math.max(0,t-state.lastSegmentWallMs);if(state.segmentVisible)state.activeMs+=d;else state.inactiveMs+=d;state.lastSegmentWallMs=t;}
function currentActiveMs(){if(!state.started)return 0;commitSegment();return state.activeMs;}
function currentAdjustedActiveMs(){if(!state.started)return 0;const a=currentActiveMs();const open=state.exclusionDepth>0?Math.max(0,a-state.exclusionStartActiveMs):0;return Math.max(0,a-state.excludedActiveMs-open);}
function logEvent(event,details){if(!state.started)return;state.timingEvents.push(Object.assign({event,activeOffsetMs:Math.round(currentActiveMs()),adjustedActiveOffsetMs:Math.round(currentAdjustedActiveMs()),wallOffsetMs:Math.max(0,now()-state.startWallMs)},details||{}));}
function start(startDate){const s=startDate instanceof Date?startDate.getTime():Number(startDate||now());Object.assign(state,{started:true,startWallMs:s,lastSegmentWallMs:now(),segmentVisible:!document.hidden,activeMs:0,inactiveMs:0,excludedActiveMs:0,exclusionDepth:0,exclusionStartActiveMs:0,openEvents:new Map(),eventCounter:0,firstAnswered:new Set(),answers:{},itemShownAdjustedMs:{},itemLatencyMs:{},timingEvents:[],answerOrder:[],visibilityEvents:[{state:document.hidden?'hidden':'visible',offsetMs:0}],changedResponseCount:0,orderCounter:0});}
function beginEvent(name,meta,excludeFromLatency=true){if(!state.started)return null;const token=name+':'+(++state.eventCounter),activeAtStart=currentActiveMs();if(excludeFromLatency){if(state.exclusionDepth===0)state.exclusionStartActiveMs=activeAtStart;state.exclusionDepth++;}state.openEvents.set(token,{name,meta:meta||{},excludeFromLatency,wallStartMs:now(),activeStartMs:activeAtStart});logEvent(name+'_start',Object.assign({token},meta||{}));return token;}
function endEvent(token,meta){if(!state.started||!token)return;const evt=state.openEvents.get(token);if(!evt)return;const activeAtEnd=currentActiveMs();if(evt.excludeFromLatency){state.exclusionDepth=Math.max(0,state.exclusionDepth-1);if(state.exclusionDepth===0){state.excludedActiveMs+=Math.max(0,activeAtEnd-state.exclusionStartActiveMs);state.exclusionStartActiveMs=0;}}const endMeta=Object.assign({},evt.meta,meta||{},{token,durationMs:Math.max(0,now()-evt.wallStartMs),activeDurationMs:Math.max(0,activeAtEnd-evt.activeStartMs)});state.openEvents.delete(token);logEvent(evt.name+'_end',endMeta);}
function markScoredItemShown(step){if(!state.started)return;const key='Q'+String(step).padStart(2,'0');if(state.firstAnswered.has(key))return;const t=currentAdjustedActiveMs();state.itemShownAdjustedMs[key]=t;logEvent('scored_item_display',{item:key});}
function markAttentionShown(index){if(!state.started)return;logEvent('attention_check_display',{attentionCheck:index});}
function recordScoredResponse(step,response){if(!state.started)return;const key='Q'+String(step).padStart(2,'0');const adj=currentAdjustedActiveMs(),act=currentActiveMs();const previous=Object.prototype.hasOwnProperty.call(state.answers,key)?state.answers[key]:null;const changed=previous!==null&&previous!==response;const first=!state.firstAnswered.has(key);state.orderCounter++;if(first){const shown=Number.isFinite(state.itemShownAdjustedMs[key])?state.itemShownAdjustedMs[key]:adj;const latency=Math.max(0,adj-shown);state.firstAnswered.add(key);state.itemLatencyMs[key]=Math.round(latency);state.answerOrder.push(key);}else if(changed){state.changedResponseCount++;}state.answers[key]=response;state.timingEvents.push({event:'scored_response',item:key,response,changed,firstAnswer:first,latencyMs:first?state.itemLatencyMs[key]:null,activeOffsetMs:Math.round(act),adjustedActiveOffsetMs:Math.round(adj),wallOffsetMs:Math.max(0,now()-state.startWallMs),order:state.orderCounter});}
function recordAttentionResponse(index,response){if(!state.started)return;logEvent('attention_check_response',{attentionCheck:index,response});}
function visibilityChanged(){if(!state.started)return;commitSegment();state.segmentVisible=!document.hidden;state.visibilityEvents.push({state:state.segmentVisible?'visible':'hidden',offsetMs:Math.max(0,now()-state.startWallMs)});}
document.addEventListener('visibilitychange',visibilityChanged);
function mean(v){return v.length?v.reduce((a,b)=>a+b,0)/v.length:0;}function median(v){if(!v.length)return 0;const x=v.slice().sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;}function sampleSd(v){if(v.length<2)return 0;const a=mean(v);return Math.sqrt(v.reduce((s,x)=>s+Math.pow(x-a,2),0)/(v.length-1));}function longestFastSequence(v,t){let l=0,c=0;for(const x of v){if(x<t){c++;l=Math.max(l,c)}else c=0}return l;}
function snapshot(){if(state.started)commitSegment();const ordered=[];for(let i=1;i<=81;i++){const k='Q'+String(i).padStart(2,'0');if(Number.isFinite(state.itemLatencyMs[k]))ordered.push(state.itemLatencyMs[k]);}const avg=mean(ordered),sd=sampleSd(ordered);return{activeSeconds:Math.round(state.activeMs/1000),inactiveSeconds:Math.round(state.inactiveMs/1000),excludedActiveSeconds:Math.round(state.excludedActiveMs/1000),medianResponseLatencyMs:Math.round(median(ordered)),meanResponseLatencyMs:Math.round(avg),responseLatencySdMs:Math.round(sd),responseLatencyCv:avg?Number((sd/avg).toFixed(4)):0,firstHalfMedianLatencyMs:Math.round(median(ordered.slice(0,40))),secondHalfMedianLatencyMs:Math.round(median(ordered.slice(40))),fastResponsesUnder1Sec:ordered.filter(v=>v<1000).length,fastResponsesUnder2Sec:ordered.filter(v=>v<2000).length,fastResponsesUnder3Sec:ordered.filter(v=>v<3000).length,longestFastResponseSequenceUnder2Sec:longestFastSequence(ordered,2000),changedResponseCount:state.changedResponseCount,itemLatencyMs:Object.assign({},state.itemLatencyMs),timingEvents:state.timingEvents.slice(),answerOrder:state.answerOrder.slice(),visibilityEvents:state.visibilityEvents.slice()};}
window.RISE_LATENCY={start,beginEvent,endEvent,markScoredItemShown,markAttentionShown,recordScoredResponse,recordAttentionResponse,snapshot};
})();
